<a href="https://colab.research.google.com/github/cedrismjeon/MachineLearning_yahak/blob/main/4.%20Iris%20Flower.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#라이브러리 사용
import pandas as pd
import tensorflow as tf

In [ ]:
#과거의 데이터 준비
file = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(file)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [ ]:
#원핫인코딩
encoding = pd.get_dummies(iris)
encoding.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [ ]:
print(encoding.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [ ]:
#독립변수, 종속변수
independent = encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dependent = encoding[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(independent.shape, dependent.shape)

(150, 4) (150, 3)


In [ ]:
#모델의 구조 만들기
X = tf.keras.layers.Input([4])
Y = tf.keras.layers.Dense(3, activation = 'softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [ ]:
#모델을 fit하기
model.fit(independent, dependent, epochs=1000)

Epoch 1/1000
5/5 [==============================] - 1s 2ms/step - loss: 1.9917 - accuracy: 0.3229
Epoch 2/1000
5/5 [==============================] - 0s 3ms/step - loss: 1.8428 - accuracy: 0.3420
Epoch 3/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.7386 - accuracy: 0.3555
Epoch 4/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.7622 - accuracy: 0.3234
Epoch 5/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.7059 - accuracy: 0.3229
Epoch 6/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.5615 - accuracy: 0.3798
Epoch 7/1000
5/5 [==============================] - 0s 3ms/step - loss: 1.6568 - accuracy: 0.3116
Epoch 8/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.4876 - accuracy: 0.3789
Epoch 9/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.5529 - accuracy: 0.3164
Epoch 10/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.4551 - accuracy: 0.3516
Epoch 11/1000
5/5 [

In [ ]:
#모델을 이용하기
print(model.predict(independent[:5]))
print(dependent[:5])

[[9.9953282e-01 4.6716104e-04 4.2021259e-08]
 [9.9733680e-01 2.6626620e-03 4.7327947e-07]
 [9.9905020e-01 9.4964309e-04 1.5391295e-07]
 [9.9733943e-01 2.6599013e-03 7.5592112e-07]
 [9.9966943e-01 3.3061576e-04 3.0989298e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
